export default function AIDisclaimer({ className = '' }) {
  return (
    <div className={`bg-amber-50 border border-amber-200 rounded-lg px-4 py-3 flex items-start gap-3 ${className}`}>
      <svg className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <div>
        <p className="text-sm font-medium text-amber-800">AI-Generated Content</p>
        <p className="text-xs text-amber-700 mt-0.5">
          This result is generated by AI and may contain errors. Always verify with official records
          at{' '}
          <a
            href="https://ecourts.gov.in"
            target="_blank"
            rel="noopener noreferrer"
            className="underline font-medium hover:text-amber-900"
          >
            ecourts.gov.in
          </a>{' '}
          or consult a qualified lawyer before taking legal action.
        </p>
      </div>
    </div>
  );
}
