/**
 * Browser-based PDF generation using printable HTML.
 * Opens a print dialog with formatted content — works on all devices.
 * No external dependencies needed.
 */

export function downloadAsPdf(title, sections) {
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${escapeHtml(title)} - Nyaya</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Georgia', serif; color: #1a1a1a; padding: 40px; line-height: 1.6; }
    .header { border-bottom: 2px solid #1e3a5f; padding-bottom: 16px; margin-bottom: 24px; }
    .header h1 { font-size: 22px; color: #1e3a5f; }
    .header .subtitle { font-size: 12px; color: #666; margin-top: 4px; }
    .section { margin-bottom: 20px; }
    .section h2 { font-size: 16px; color: #1e3a5f; border-bottom: 1px solid #ddd; padding-bottom: 4px; margin-bottom: 8px; }
    .section p, .section li { font-size: 13px; margin-bottom: 4px; }
    .section ul, .section ol { padding-left: 20px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: bold; }
    .badge-green { background: #dcfce7; color: #166534; }
    .badge-red { background: #fee2e2; color: #991b1b; }
    .badge-yellow { background: #fef9c3; color: #854d0e; }
    .disclaimer { margin-top: 32px; padding: 12px; border: 1px solid #fbbf24; background: #fffbeb; border-radius: 4px; font-size: 11px; color: #92400e; }
    .footer { margin-top: 32px; border-top: 1px solid #ddd; padding-top: 12px; font-size: 10px; color: #999; text-align: center; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(title)}</h1>
    <div class="subtitle">Generated by Nyaya Legal Platform &bull; ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
  </div>
  ${sections.map(s => `
  <div class="section">
    <h2>${escapeHtml(s.heading)}</h2>
    ${s.content}
  </div>`).join('')}
  <div class="disclaimer">
    <strong>AI-Generated Content Disclaimer:</strong> This document is generated by AI and is for informational purposes only.
    It does not constitute legal advice. Always verify with official records at ecourts.gov.in and consult a qualified lawyer before taking legal action.
  </div>
  <div class="footer">Nyaya - AI-Powered Indian Legal Platform &bull; nyaya-legal.vercel.app</div>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (win) {
    win.document.write(html);
    win.document.close();
    setTimeout(() => win.print(), 300);
  }
}

function escapeHtml(text) {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

/**
 * Helper to build bail result PDF sections
 */
export function bailResultToPdfSections(result) {
  const sections = [];

  if (result.sections_analysis?.length) {
    sections.push({
      heading: "Sections Analysis",
      content: `<ul>${result.sections_analysis.map(s =>
        `<li><strong>Section ${escapeHtml(s.section)}</strong> — ${escapeHtml(s.name)} (Max: ${s.max_years} years, ${s.bailable ? 'Bailable' : 'Non-bailable'})</li>`
      ).join('')}</ul>
      <p>Days in custody: <strong>${result.days_in_custody}</strong> | Chargesheet deadline: <strong>${result.chargesheet_deadline_days} days</strong></p>`,
    });
  }

  if (result.eligibility?.length) {
    for (const e of result.eligibility) {
      sections.push({
        heading: e.type,
        content: `
          <p><span class="badge ${e.eligible ? 'badge-green' : e.urgency === 'WATCH' ? 'badge-yellow' : 'badge-red'}">${e.eligible ? 'ELIGIBLE' : e.urgency}</span></p>
          <p>${escapeHtml(e.explanation)}</p>
          <p><strong>Legal Basis:</strong> ${escapeHtml(e.legal_basis || '')}</p>
          <p><strong>Action:</strong> ${escapeHtml(e.action || '')}</p>
          ${e.precedent ? `<p><strong>Precedent:</strong> ${escapeHtml(e.precedent)}</p>` : ''}`,
      });
    }
  }

  if (result.summary) {
    sections.push({
      heading: "Recommendation",
      content: `<p><strong>${escapeHtml(result.summary.recommendation)}</strong></p>
        <p>Strongest ground: ${escapeHtml(result.summary.strongest_ground)}</p>`,
    });
  }

  return sections;
}
